name: GitLeaks Scan

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]    

 

jobs:
  gitleaks:
    runs-on: ubuntu-latest

 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

 

    - name: Install GitLeaks
      run: |
        wget -q -O gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz
        ls -l
        tar -xzvf gitleaks.tar.gz
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/

 
    - name: Run GitLeaks
      run: |
        gitleaks detect --redact

    - name: Download OWASP Dependency-Check
      run: |
       wget -q -O dependency-check-8.4.0-release.zip  https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
       ls -l
       unzip -qq dependency-check-8.4.0-release.zip   

    - name: Run OWASP Dependency-Check
      run: ./dependency-check/bin/dependency-check.sh --scan ./ --format HTML --project "Dependencychecker_DevOpsTest" --out ./report   

