name: gitleaks-sast-sca-scan

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]    

 

jobs:
  gitleaks-sast-sca-scanning:
    runs-on: ubuntu-latest

 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

 

    - name: Install GitLeaks
      run: |
        wget -q -O gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz
        ls -l
        tar -xzvf gitleaks.tar.gz
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/

 
    - name: Run GitLeaks
      run: |
        gitleaks detect --redact
  
  BuildWithGitHubActions:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml


    - name: Download OWASP Dependency-Check
      run: |
       wget -q -O dependency-check-8.4.0-release.zip  https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
       ls -l
       unzip -qq dependency-check-8.4.0-release.zip   

    - name: Run OWASP Dependency-Check
      run: ./dependency-check/bin/dependency-check.sh --scan ./ --format HTML --project "Dependencychecker_DevOpsTest" --out ./report
    - name: Upload OWASP Dependency-Check Report
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-report
        path: ./report
 
    - name: Download FindSecBugs
      run: |
       wget -q -O findsecbugs-cli-1.12.0.zip https://github.com/find-sec-bugs/find-sec-bugs/releases/download/version-1.12.0/findsecbugs-cli-1.12.0.zip 
       unzip -qq findsecbugs-cli-1.12.0.zip
       chmod 755 findsecbugs.sh 
       chmod +x findsecbugs.sh
       ls -l
    
    - name: Run FindSecBugs
      env: 
        JAVA_HOME: /opt/jdk
      run: ./findsecbugs.sh -progress -output findsecbugs-results.html -html target/*.jar

    - name: Upload FindSecBugs Report
      uses: actions/upload-artifact@v2
      with:
        name: findsecbugs-report
        path: findsecbugs-results.html

